const prelimQuestions = [
    { q: "It refers to the activity combining technical knowledge with the ability to organize and coordinate worker power, materials, machinery, and money.", a: "Engineering management" },
    { q: "It is a creative problem-solving process of planning, organizing, leading, and controlling an organization's resources to achieve its mission and objectives.", a: "Management" },
    { q: "These managers do not happen as a matter of chance, although luck is a contributory factor.", a: "Successful engineering managers" },
    { q: "One of the three general preconditions for achieving lasting success as a manager according to Kreitner, referring to capacity.", a: "Ability" },
    { q: "One of the three general preconditions for achieving lasting success as a manager according to Kreitner, referring to drive or desire.", a: "Motivation to manage" },
    { q: "One of the three general preconditions for achieving lasting success as a manager according to Kreitner, referring to a favorable chance or climate.", a: "Opportunity" },
    { q: "It refers to the capacity of an engineer manager to achieve organizational objectives effectively and efficiently.", a: "Managerial ability" },
    { q: "According to Higgins, it refers to a description of whether objectives are accomplished.", a: "Effectiveness" },
    { q: "A description of the relative amount of resources used in obtaining effectiveness.", a: "Efficiency" },
    { q: "A management researcher who developed a psychometric instrument to measure objectively an individual's motivation to manage.", a: "John B. Miner" },
    { q: "They are known for their great contributions to the development of the world's civilization.", a: "Engineers" },
    { q: "It describes the distinct approaches that different managers take to support and guide a team at work.", a: "Management styles" },
    { q: "This manager centralizes the decision-making process and represents the most top-down approach to management.", a: "Autocratic management style" },
    { q: "One type of autocratic management that puts decision-making totally in the hands of managers but encourages them to share the logic and rationale behind decisions.", a: "Persuasive management style" },
    { q: "A form of unilateral decision-making where the team's best interests are always kept in mind.", a: "Paternalistic management style" },
    { q: "In this style, managers collaborate with their team members to distribute the decision-making process.", a: "Democratic management style" },
    { q: "A subset of the democratic management style where managers are consistently looking for feedback from their team and trying to improve.", a: "Consultative management style" },
    { q: "This democratic style strives to create a culture that encourages adaptability, innovation, and problem-solving, focusing on long-term development.", a: "Transformational management style" },
    { q: "This style literally translates to 'let it go' in French and represents the most hands-off managers.", a: "Laissez-faire management style" },
    { q: "A type of laissez-faire management more interested in educating team members about the larger vision of the organization rather than day-to-day tasks.", a: "Visionary management style" },
    { q: "A system where managers and team members only interact when managers are assigning them tasks.", a: "Delegative management style" },
    { q: "Behaviors adopted to perform various management functions, developed by Professor Henry Mintzberg.", a: "Managerial roles" },
    { q: "A category of roles where the manager is responsible for providing ideas and information and interacting with other people.", a: "Interpersonal roles" },
    { q: "A category of roles where the manager is responsible for generating or collecting data, then processing and sharing information.", a: "Informational roles" },
    { q: "A category of roles where the manager uses the knowledge gathered to move the organization towards its goals.", a: "Decisional roles" },
    { q: "An interpersonal role associated with upper management, acting as a representative and promoting the company externally.", a: "Figurehead" },
    { q: "An interpersonal role where managers oversee the performance of an organization, set goals, and communicate those to all team members.", a: "Leader" },
    { q: "An interpersonal role responsible for developing and maintaining internal and external relationships, acting as a bridge.", a: "Liaison" },
    { q: "An informational role where managers actively search for information to assess the business's effectiveness and identify problems.", a: "Monitor" },
    { q: "An informational role where the manager collects strategic and technical information from different sources and conveys it to appropriate people.", a: "Disseminator" },
    { q: "An informational role where the manager is the face of their team or entire organization at conferences or shareholder meetings.", a: "Spokesperson" },
    { q: "A decisional role where the manager decides how to best assign organizational assets like time and budget.", a: "Resource Allocator" },
    { q: "A decisional role involving discussing terms on behalf of a department or business to achieve the best possible outcome.", a: "Negotiator" },
    { q: "Certain attributes or abilities that an executive should possess in order to fulfill specific tasks in an organization.", a: "Management skills" },
    { q: "Skills that give the managers the ability and the knowledge to use a variety of techniques to achieve their objectives.", a: "Technical skills" },
    { q: "Skills that involve the knowledge and ability for abstract thinking and formulating ideas.", a: "Conceptual skills" },
    { q: "Skills that present the managers' ability to interact, work or relate effectively with people.", a: "Human skills" },
    { q: "It refers to one's ability to organize activities in line with set guidelines while remaining within the limits of available resources.", a: "Planning" },
    { q: "This management skill involves the flow of information within the organization, whether formal or informal.", a: "Communication" },
    { q: "A vital management skill where making proper and right choices results in the success of the organization.", a: "Decision-making" },
    { q: "The act of passing on work-related tasks and/or authorities to other employees or subordinates.", a: "Delegation" },
    { q: "An essential skill involving identifying a certain situation and then finding the best way to handle it to get the best solution.", a: "Problem-solving" },
    { q: "The ability to bring forth a desired behavior or response from the employees, categorized as intrinsic and extrinsic.", a: "Motivating" },
    { q: "The line of division that exists between various managerial positions in an organization.", a: "Levels of management" },
    { q: "This level of management consists of an organization's board of directors and the chief executive or managing director.", a: "Top Level of Management" },
    { q: "This level of management includes branch and departmental managers who are directly accountable for their departments' functioning.", a: "Middle Level of Management" },
    { q: "This level of management consists of supervisors, foremen, and section officers concerned with day-to-day workflow.", a: "Lower Level of Management" },
    { q: "It includes the duties and tasks which you carry because of your position or function.", a: "Responsibility" },
    { q: "It is the power and rights you are given, so you can effectively discharge your responsibility.", a: "Authority" },
    { q: "It refers to your liability or answerability as supervisor for the way in which your organizational obligations are discharged.", a: "Accountability" }
];

const midtermQuestions = [
    { q: "It is the sending and receiving of information and involves a sender who initiates and encodes a message.", a: "Communication" },
    { q: "The person who initiates communication and transfers thoughts into a message.", a: "Sender" },
    { q: "The person who is meant to receive the communication and interpret the message.", a: "Receiver" },
    { q: "The process of transferring thoughts into a message that can be transmitted.", a: "Encoding" },
    { q: "The process of interpreting a message back into information that can be understood.", a: "Decoding" },
    { q: "The medium through which the information is conveyed.", a: "Channel" },
    { q: "In an interactive communication process, the receiver can send this to the sender to indicate how the message was interpreted.", a: "Feedback" },
    { q: "This reduces the cost associated with conflicts, misunderstandings, and mistakes.", a: "Effective communication" },
    { q: "It fosters a positive work environment, increases productivity, and helps in achieving organizational goals.", a: "Effective communication" },
    { q: "It ensures that messages are understood exactly as intended, minimizing the chances of errors and rework.", a: "Effective communication" },
    { q: "The linchpin that connects top-level management with the rest of the team, providing clarity, transparency, and unity.", a: "Management communication" },
    { q: "One of the 7 C's stating information should be concise, and easy to understand, avoiding jargon.", a: "Clarity" },
    { q: "One of the 7 C's stating messages should be brief and to the point without unnecessary details.", a: "Conciseness" },
    { q: "One of the 7 C's ensuring verbal communication always follows a logical and organized structure.", a: "Coherence" },
    { q: "One of the 7 C's maintaining uniformity in messaging and branding to prevent confusion.", a: "Consistency" },
    { q: "One of the 7 C's highlighting accuracy and verifying the information you're sharing to avoid errors.", a: "Correctness" },
    { q: "One of the 7 C's meaning to be mindful of the needs, perspectives, and interests of your audience.", a: "Consideration" },
    { q: "One of the 7 C's ensuring communication provides all necessary and accurate information to avoid need for follow-ups.", a: "Completeness" },
    { q: "These prevent us from understanding messages as the senders intend, causing miscommunication.", a: "Communication barriers" },
    { q: "A communication barrier caused by not knowing much about the other person's background or speaking different dialects.", a: "Differences in language and culture" },
    { q: "A communication barrier posed by your physical location or distance from someone.", a: "Barriers of the physical environment" },
    { q: "A communication barrier involving differing beliefs and experiences, like rejecting suggestions based on personal bias.", a: "Differences in perception" },
    { q: "A communication barrier where miscommunication happens due to making assumptions and using stereotypes.", a: "Attitude" },
    { q: "A communication barrier related to not feeling well, having a health problem, or experiencing strong feelings like anger or fear.", a: "Emotional and psychological conditions" },
    { q: "A type of verbal barrier happening when people can't understand each other because they speak different languages.", a: "Language barriers" },
    { q: "A verbal barrier where words requiring a specific level of understanding lead to the person not receiving the message well.", a: "Use of jargon and technical terms" },
    { q: "A non-verbal barrier involving fidgeting or constant movement that can signal someone may be lying.", a: "Body language and gestures" },
    { q: "A non-verbal barrier showing our emotions better than any language, like lowering the brow to show anger.", a: "Facial expressions" },
    { q: "A non-verbal barrier that can show confidence but might also seem threatening or its absence means discomfort.", a: "Eye contact" },
    { q: "A non-verbal barrier where being further away makes it harder to communicate.", a: "Distance and physical space" },
    { q: "A written barrier where using the wrong words and phrasing leads to misunderstanding despite having a common language.", a: "Poor grammar and spelling" },
    { q: "A written barrier where text symbols like commas give different meanings if misused.", a: "Incorrect use of punctuation" },
    { q: "A written barrier where sentences lack logical flow, making them hard to understand.", a: "Lack of organization and coherence" },
    { q: "A written barrier where text is not readable, requiring well-written tools to avoid confusion.", a: "Poor handwriting or typewriting" },
    { q: "A critical skill for leaders that ensures clear, transparent, and unifying information flow within an organization.", a: "Effective management communication" },
    { q: "The process of sharing information between supervisors and subordinates to facilitate daily operations.", a: "Management communication" },
    { q: "When implemented successfully, it minimizes misunderstandings and aligns everyone towards common objectives.", a: "Effective communication" },
    { q: "It empowers employees, builds trust between staff and leaders, and boosts overall team morale.", a: "Effective management communication" },
    { q: "This type of communication is essential for executing strategies, managing change, and guiding teams.", a: "Management communication" },
    { q: "It is the extended continuous service with a company or organization.", a: "Seniority" },
    { q: "A benefit of seniority where employees may be more likely to stay with one organization for a longer period.", a: "Employee loyalty" },
    { q: "A benefit of seniority granting the first option to request extra shifts, usually coming with additional pay scales.", a: "Overtime" },
    { q: "A benefit of seniority where companies may choose to keep those with the most history during staff downsizing and layoffs.", a: "Job security" },
    { q: "A benefit of seniority providing more paid vacation, sick days, and personal days per year.", a: "Paid time off" },
    { q: "A benefit of seniority where internal candidates are chosen based on their prerequisite years of service for advancement.", a: "Promotions" },
    { q: "A benefit of seniority allowing the choice of which job sites to work at or which calls to take.", a: "Preferred jobs" },
    { q: "The lowest level of seniority, suitable for recent graduates or those starting a career in a new field.", a: "Entry-level" },
    { q: "A level of seniority where employees typically have established experience for five or more years and may serve as supervisors.", a: "Mid-level" },
    { q: "A level of seniority also known as C-level executives, requiring high level of experience and a history of exceptional performance.", a: "Senior-level" },
    { q: "These agreements with trade unions make the rules about hierarchical structures, proving that seniority systems are completely legal.", a: "Collective agreements" }
];

const finalQuestions = [
    { q: "It has been described as a social process involving responsibility for economical and effective planning and regulation of the operation of an enterprise.", a: "Management" },
    { q: "Experts who gave the most widely accepted functions of management: Planning, Organizing, Staffing, Directing and Controlling.", a: "Koontz and O'Donnel" },
    { q: "An expert who stated 'There are four fundamental functions of management i.e. planning, organizing, actuating and controlling'.", a: "George and Jerry" },
    { q: "An expert who stated 'To manage is to forecast and plan, to organize, to command, & to control'.", a: "Henry Fayol" },
    { q: "He has given a keyword 'POSDCORB' for the functions of management.", a: "Luther Gullick" },
    { q: "It is deciding in advance what to do, how to do and who is to do it. It bridges the gap between where we are to where we want to go.", a: "Planning" },
    { q: "This step in planning focuses the attention of managers on the end results to be achieved and provides a rationale for undertaking various activities.", a: "Establishment of objectives" },
    { q: "These are the assumptions about the lively shape of events in future that serve as a basis of planning.", a: "Planning premises" },
    { q: "Premises that are controllable, such as capital investment policy and management labour relations.", a: "Internal premises" },
    { q: "Premises that are non-controllable, such as socio-economic, political and economical changes.", a: "External premises" },
    { q: "This step in planning evaluates pros and cons in the light of resources available to choose the best option.", a: "Choice of alternative course of action" },
    { q: "A characteristic of planning indicating it is made to achieve the desired objective of the business.", a: "Planning is goal-oriented" },
    { q: "A characteristic of planning indicating it is done for the future and based on forecasting.", a: "Planning is looking ahead" },
    { q: "A characteristic of planning indicating it lays the foundation for other functions of management.", a: "Planning is the primary function of management" },
    { q: "A characteristic of planning indicating it is a never-ending function due to the dynamic business environment.", a: "Planning is a continuous process" },
    { q: "It is a function in which the synchronization and combination of human, physical and financial resources takes place.", a: "Organizing" },
    { q: "An expert who said 'Organizing is a function by which the concern is able to define the role positions, the jobs related and the co-ordination between authority and responsibility'.", a: "Chester Barnard" },
    { q: "A step in organizing where all tasks to be performed in a concern are grouped and classified into units.", a: "Identification of activities" },
    { q: "A step in organizing involving dividing the whole concern into independent units and departments.", a: "Departmentally organizing the activities" },
    { q: "A step in organizing involving giving a rank in order to the managerial positions, also called hierarchy.", a: "Classifying the authority" },
    { q: "A step in organizing where relationships are established among various groups and each individual is made aware of their accountability.", a: "Co-ordination between authority and responsibility" },
    { q: "It involves manning the organization structure through proper and effective selection, appraisal and development of the personnels.", a: "Staffing" },
    { q: "An expert who stated 'Staffing pertains to recruitment, selection, development and compensation of subordinates'.", a: "Theo Haimann" },
    { q: "The very first step in staffing which involves forecasting and determining the future manpower needs of the concern.", a: "Manpower requirements" },
    { q: "A step in staffing where the concern invites and solicits applications from desirable candidates.", a: "Recruitment" },
    { q: "The screening step of staffing where suitable candidates are appointed as per the requirements.", a: "Selection" },
    { q: "A step in staffing where appointed candidates are made familiar to the work units and work environment.", a: "Orientation and Placement" },
    { q: "The function of management that involves actuating the organizational methods to work efficiently for achieving organizational purposes.", a: "Directing" },
    { q: "A component of directing that involves inspiring and encouraging employees to take required action.", a: "Motivation" },
    { q: "A component of directing involving the process of guiding and instructing people to do work in the right manner.", a: "Supervision" },
    { q: "A component of directing representing the process by which a manager guides and influences the work of his subordinates in desired direction.", a: "Leadership" },
    { q: "A component of directing involving the exchange of information between two or more persons.", a: "Communication" },
    { q: "The measurement and correction of performance activities of subordinates in order to make sure that the enterprise objectives and plans are being accomplished.", a: "Controlling" },
    { q: "A step in controlling that involves setting benchmarks or criteria against which actual performance will be measured.", a: "Establishment of standard performance" },
    { q: "A step in controlling that involves evaluating the actual work done by employees.", a: "Measurement of actual performance" },
    { q: "A step in controlling that finds out the deviations and causes of deviations.", a: "Comparison of actual performance with the standards" },
    { q: "A step in controlling that involves taking steps to prevent deviations from recurring in the future.", a: "Corrective action" },
    { q: "A characteristic of controlling indicating it applies to all levels of management.", a: "Controlling is a pervasive function" },
    { q: "A characteristic of controlling indicating it looks back at the performance achieved.", a: "Controlling is a backward-looking function" },
    { q: "A characteristic of controlling indicating it seeks to improve future performance.", a: "Controlling is a forward-looking function" },
    { q: "It is a dynamic process consisting of various elements and activities common to each and every manager irrespective of his level or status.", a: "Management" },
    { q: "These provide a rationale for undertaking various activities as well as indicate direction of efforts in planning.", a: "Objectives" },
    { q: "For goals that cannot be specified in quantitative terms like performance, they should be specified in these terms.", a: "Qualitative terms" },
    { q: "It is rightly said that a well ___ is half done, referring to a preparatory step in management.", a: "Plan" },
    { q: "These planning premises are controllable by the management.", a: "Internal premises" },
    { q: "These planning premises are non-controllable like socio-economic and political changes.", a: "External premises" },
    { q: "It is a mental predisposition for things to happen in future and a synthesis of forecast.", a: "Plan" },
    { q: "This organization of dividing the whole concern into independent units and departments.", a: "Departmentation" },
    { q: "This activity of giving a rank in order to the managerial positions.", a: "Hierarchy" },
    { q: "This function of management follows planning and helps in achievement of results.", a: "Organizing" }
];

const allQuestions = [...prelimQuestions, ...midtermQuestions, ...finalQuestions];
